### ISSUE TITLE
Error while fetching User Data: SocketException: Failed host lookup: 'api.linkfive.io'

### ISSUE THREAD

**Issue by dukesx** [LinkFive/flutter-purchases-sdk#7]
I am using the provider package. I did all the steps as mentioned in documentation but when i start the dev app, i am getting this error.

```
Error while fetching User Data: SocketException: Failed host lookup: 'api.linkfive.io'
```

I am also unable to access the address with browser.

**Comment by lwwells** [comment]
I am facing the same issue, Oct 1 2023.   How was this resolved?  Any updates as to what we're doing wrong?

**Comment by AlexanderThiele** [comment]
Hey @lwwells 
are you maybe behind a corporate proxy? can you try a manual lookup with e.g. the Terminal: $ `nslookup api.linkfive.io`?
